### ISSUE TITLE
sometimes it works and sometimes say sdk is not configured ? please help me to solve this issue

### ISSUE THREAD

**Issue by noshair** [AnchorFreePartner/hydrasdk-demo-android#104]

**Comment by timoshenkoav** [comment]
please share logs and code that fails

**Comment by noshair** [comment]
which logs on android studio or dashboard of anchor

**Comment by timoshenkoav** [comment]
adb logcat without any filters

**Comment by noshair** [comment]
java.lang.RuntimeException: Unable to pause activity {best.simplona.vpn.proxy.server.fire.tablets.tv/best.simplona.vpn.proxy.server.fire.tablets.tv.activity.MainActivity}: java.lang.NullPointerException: Cannot find initialized sdk instance with name [vpnAccess]

**Comment by noshair** [comment]
at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4141)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4107)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4081)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4055)
        at android.app.ActivityThread.-wrap16(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1736)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.NullPointerException: Cannot find initialized sdk instance with name [vpnAccess]
        at com.anchorfree.toolkit.utils.ObjectHelper.checkNotNull(ObjectHelper.java:65)
        at com.anchorfree.toolkit.utils.ObjectHelper.requireNonNull(ObjectHelper.java:42)
        at com.anchorfree.sdk.UnifiedSDK.getInstance(UnifiedSDK.java:152)
        at com.anchorfree.sdk.UnifiedSDK.getInstance(UnifiedSDK.java:157)
        at best.simplona.vpn.proxy.server.fire.tablets.tv.activity.UIActivity.updateUI(UIActivity.java:404)
        at best.simplona.vpn.proxy.server.fire.tablets.tv.activity.UIActivity.stopUIUpdateTask(UIActivity.java:339)
        at best.simplona.vpn.proxy.server.fire.tablets.tv.activity.UIActivity.onPause(UIActivity.java:249)
        at android.app.Activity.performPause(Activity.java:7521)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1416)

**Comment by noshair** [comment]
:26.044 12825-12825/com.northghost.hydraclient E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.northghost.hydraclient, PID: 12825
    java.lang.RuntimeException: Unable to pause activity {com.northghost.hydraclient/com.northghost.hydraclient.activity.MainActivity}: java.lang.NullPointerException: Cannot find initialized sdk instance with name [vpnAccess]
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4141)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4107)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4081)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4055)
        at android.app.ActivityThread.-wrap16(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1744)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.NullPointerException: Cannot find initialized sdk instance with name [vpnAccess]
        at com.anchorfree.toolkit.utils.ObjectHelper.checkNotNull(ObjectHelper.java:65)
        at com.anchorfree.toolkit.utils.ObjectHelper.requireNonNull(ObjectHelper.java:42)
        at com.anchorfree.sdk.UnifiedSDK$-CC.getInstance(UnifiedSDK.java:152)
        at com.anchorfree.sdk.UnifiedSDK$-CC.getInstance(UnifiedSDK.java:157)
        at com.northghost.hydraclient.activity.UIActivity.updateUI(UIActivity.java:268)
        at com.northghost.hydraclient.activity.UIActivity.stopUIUpdateTask(UIActivity.java:217)
        at com.northghost.hydraclient.activity.UIActivity.onPause(UIActivity.java:136)
        at android.app.Activity.performPause(Activity.java:7521)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1416)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4130)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4107) 
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4081) 
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4055) 
        at android.app.ActivityThread.-wrap16(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1744) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7000) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by noshair** [comment]
**### _Same thing on your app_**

:26.044 12825-12825/com.northghost.hydraclient E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.northghost.hydraclient, PID: 12825
    java.lang.RuntimeException: Unable to pause activity {com.northghost.hydraclient/com.northghost.hydraclient.activity.MainActivity}: java.lang.NullPointerException: Cannot find initialized sdk instance with name [vpnAccess]
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4141)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4107)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4081)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4055)
        at android.app.ActivityThread.-wrap16(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1744)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.NullPointerException: Cannot find initialized sdk instance with name [vpnAccess]
        at com.anchorfree.toolkit.utils.ObjectHelper.checkNotNull(ObjectHelper.java:65)
        at com.anchorfree.toolkit.utils.ObjectHelper.requireNonNull(ObjectHelper.java:42)
        at com.anchorfree.sdk.UnifiedSDK$-CC.getInstance(UnifiedSDK.java:152)
        at com.anchorfree.sdk.UnifiedSDK$-CC.getInstance(UnifiedSDK.java:157)
        at com.northghost.hydraclient.activity.UIActivity.updateUI(UIActivity.java:268)
        at com.northghost.hydraclient.activity.UIActivity.stopUIUpdateTask(UIActivity.java:217)
        at com.northghost.hydraclient.activity.UIActivity.onPause(UIActivity.java:136)
        at android.app.Activity.performPause(Activity.java:7521)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1416)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4130)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4107) 
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4081) 
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4055) 
        at android.app.ActivityThread.-wrap16(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1744) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7000) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by timoshenkoav** [comment]
@noshair Have you clicked "Init" in the app?

**Comment by timoshenkoav** [comment]
Pushed the fix for demo app

**Comment by noshair** [comment]
yes i pushed in splash screen

**Comment by noshair** [comment]
first thing in app is this SharePrefrences is not working so i put the hardcode link and carrier id and now it's working but getting other problem

**Comment by timoshenkoav** [comment]
dont understand. What do you mean SharePrefrences is not working?

**Comment by noshair** [comment]
String url = prefs.getString(BuildConfig.STORED_HOST_URL_KEY, BuildConfig.BASE_HOST);
        String carrierId = prefs.getString(BuildConfig.STORED_CARRIER_ID_KEY, BuildConfig.BASE_CARRIER_ID);

After these lines it's not goes to if condition
  if (!TextUtils.isEmpty(url) && !TextUtils.isEmpty(carrier)) {
            ClientInfo clientInfo = ClientInfo.newBuilder().baseUrl(url).carrierId("carrier").build();

            UnifiedSDK.clearInstances();
            unifiedSDK = UnifiedSDK.getInstance(clientInfo);
            doLogin();

        } 
so i hard coded
url="https//......"
caried="21_1233"

**Comment by noshair** [comment]
then it start works
after hard coded

**Comment by timoshenkoav** [comment]
it seems you have the old code - there is no BASE_CARRIER_ID

**Comment by noshair** [comment]
private void initSDK() {
        final SharedPreferences prefs = getPrefs();
        final String url = prefs.getString(BuildConfig.STORED_HOST_URL_KEY, BuildConfig.BASE_HOST);
        final String carrier = prefs.getString(BuildConfig.STORED_CARRIER_ID_KEY, "");**_//then what is this_**
        this.url.setText(url);
        this.carrier.setText(carrier);
        if (!TextUtils.isEmpty(url) && !TextUtils.isEmpty(carrier)) {
            ClientInfo clientInfo = ClientInfo.newBuilder()
                    .baseUrl(url)
                    .carrierId(carrier)
                    .build();

            UnifiedSDK.clearInstances();
            unifiedSDK = UnifiedSDK.getInstance(clientInfo);
            loginBtnTextView.setEnabled(true);
        } else {
            loginBtnTextView.setEnabled(false);
        }
    }

**Comment by noshair** [comment]
Yes you are right then how we configure the carrier id 
in your build.gradle 
        buildConfigField "String", "BASE_CARRIER_ID", "\"*********\""
is deleted

**Comment by noshair** [comment]
Please guide me i need your help!

**Comment by noshair** [comment]
i deleted it and fix the things i am trying to update it please help me

**Comment by timoshenkoav** [comment]
by default there is no carrier configured in the app
You need to create carrier on https://developer.anchorfree.com/ and put it to the demo app UI.

**Comment by noshair** [comment]
786_33801890
this is my carrier id and how i create carrier for it

**Comment by noshair** [comment]
buildConfigField "String", "STORED_CARRIER_ID_KEY", "\"com.northghost.afvclient.CARRIER_ID_KEY\""
how do it write it

**Comment by timoshenkoav** [comment]
Your carrier id is here
![image](https://user-images.githubusercontent.com/1254369/99277867-a82c1500-282e-11eb-9049-3e717780ec79.png)

**Comment by timoshenkoav** [comment]
https://pango.gitbook.io/pango-platform/start-exploring/add-a-new-project

**Comment by noshair** [comment]
yes i have it but you are saying delete it 
buildConfigField "String", "BASE_CARRIER_ID" ,"**********"
so where should i put my carrier id in project

**Comment by noshair** [comment]
testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        buildConfigField "String", "BASE_HOST", "\"https://backend.northghost.com\""
        buildConfigField "String", "BASE_OAUTH_METHOD", "\"anonymous\""

        buildConfigField "String", "SHARED_PREFS", "\"NORTHGHOST_SHAREDPREFS\""
        buildConfigField "String", "STORED_HOST_URL_KEY", "\"com.northghost.afvclient.STORED_HOST_KEY\""
        buildConfigField "String", "STORED_CARRIER_ID_KEY", "\"com.northghost.afvclient.CARRIER_ID_KEY\""


**### this is your new code gradle so where should i put my carrier id?**

**Comment by timoshenkoav** [comment]
you should put it to carrier input
![image](https://user-images.githubusercontent.com/1254369/99278310-2be60180-282f-11eb-8bf7-2d1fbcecb3a8.png)
And click "Init"

**Comment by noshair** [comment]
ok thanks

**Comment by noshair** [comment]
**new error : Error in VPN Service**
2020-11-16 22:22:19.615 20328-20375/com.northghost.hydraclient E/USDK-NotificationManag: Got notification UI: null                                                                                                       
2020-11-16 22:22:19.616 20328-20375/com.northghost.hydraclient E/USDK-NotificationServi: return service task com.anchorfree.bolts.Task@6450650 result: android.os.Messenger@5304049 error: null                          
2020-11-16 22:22:19.617 20328-20375/com.northghost.hydraclient E/USDK-NotificationManag: Sending notification to service null                                                                                            
2020-11-16 22:22:19.619 20328-20328/com.northghost.hydraclient E/USDK-SdkNotificationSe: Update notification to: null                                                                                                    
2020-11-16 22:22:29.403 20310-20407/com.northghost.hydraclient E/USDK-UCRService: performUpload                                                                                                                   
2020-11-16 22:22:29.432 20310-20407/com.northghost.hydraclient E/USDK-UCRService: Transport upload: sdk                                                                                                           
2020-11-16 22:22:29.433 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: upload                                                                                                                          
2020-11-16 22:22:29.483 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: ---------------------------------------------------------
2020-11-16 22:22:29.484 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | Perform Request data: {"event":"connection_start","id":"1","properties":{"af_platform":"android","reason":"m_ui","notes":"{\"err |
2020-11-16 22:22:29.485 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | or_details\":\"PartnerApiException{code\u003d403message\u003dnullcontent\u003dTRAFFIC_EXCEED}at com.anchorfree.sdk.utils.Utils.e |
2020-11-16 22:22:29.486 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | xceptionFromApi(Utils.java:104)at com.anchorfree.sdk.BoltsUtils.lambda$callbackContinue$0(BoltsUtils.java:18)at com.anchorfree.s |
2020-11-16 22:22:29.487 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | dk.-$$Lambda$BoltsUtils$cGRR4Mk69SxYy708iXcAw1njWcw.then(Unknown Source:2)at com.anchorfree.bolts.Task$14.run(Task.java:914)at j |
2020-11-16 22:22:29.488 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | ava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)at java.util.concurrent.ThreadPoolExecutor$Worker. |
2020-11-16 22:22:29.489 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | run(ThreadPoolExecutor.java:636)at java.lang.Thread.run(Thread.java:764)\"}","app_version":"1.0","is_ipv6_only":"0","locale":"GB |
2020-11-16 22:22:29.490 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | ","error":"PartnerApiException:403:TRAFFIC_EXCEED","device_manufacturer":"samsung","duration":"9536","uid":10595,"protocol":"hyd |
2020-11-16 22:22:29.490 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | ra","hydra_version":"release-hydra-v5.0.4-33-g78f4a42","catime":"1605547327288","caid":"7D88165D714E4627932C4C3351AFC65B","sdk_v |
2020-11-16 22:22:29.491 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | ersion":"3.3.3","model":"SM-G610F","memory_total":2951749632,"af_hash":"Nzg2XzMzODAxODkwX2M1MGUyZDg4YzI3YTFmMzU","memory_remains |
2020-11-16 22:22:29.492 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | ":922587136,"seq_no":2,"app_release":"1","connection_type":"WiFi","android_version_name":"8.1.0","has_telephone":true,"sd_in_tun |
2020-11-16 22:22:29.493 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | nel":"0","time_zone":"+0500","app_name":"com.northghost.hydraclient","carrier":"Jazz","sdk_version_code":"403689","partner_carri |
2020-11-16 22:22:29.494 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | er":"786_33801890","app_build":-606135231,"android_sdk_int":27,"error_code":"1","time":1605547336933,"device_language":"en","ser |
2020-11-16 22:22:29.495 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | ver_protocol":"hydra"}}{"event":"connection_start_detailed","id":"4","properties":{"af_platform":"android","reason":"m_ui","not  |
2020-11-16 22:22:29.495 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | es":"{\"network_availability_test\":[{\"type\":\"http certificate\",\"url\":\"https:\\/\\/google.com\\/\",\"result\":\"ok\"},{\" |
2020-11-16 22:22:29.496 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | type\":\"captive portal\",\"url\":\"https:\\/\\/maps.google.com\\/generate_204\",\"result\":\"ok\"},{\"type\":\"network interfac |
2020-11-16 22:22:29.497 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | e\",\"result\":\"wifi\"}],\"error_details\":\"PartnerApiException{code\u003d403message\u003dnullcontent\u003dTRAFFIC_EXCEED}at c |
2020-11-16 22:22:29.497 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | om.anchorfree.sdk.utils.Utils.exceptionFromApi(Utils.java:104)at com.anchorfree.sdk.BoltsUtils.lambda$callbackContinue$0(BoltsUt |
2020-11-16 22:22:29.498 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | ils.java:18)at com.anchorfree.sdk.-$$Lambda$BoltsUtils$cGRR4Mk69SxYy708iXcAw1njWcw.then(Unknown Source:2)at com.anchorfree.bolts |
2020-11-16 22:22:29.499 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | .Task$14.run(Task.java:914)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)at java.util.concur |
2020-11-16 22:22:29.499 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | rent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)at java.lang.Thread.run(Thread.java:764)\"}","app_version":"1.0", |
2020-11-16 22:22:29.500 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | "is_ipv6_only":"0","locale":"GB","error":"PartnerApiException:403:TRAFFIC_EXCEED","device_manufacturer":"samsung","duration":"95 |
2020-11-16 22:22:29.501 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | 36","uid":10595,"protocol":"hydra","hydra_version":"release-hydra-v5.0.4-33-g78f4a42","catime":"1605547327288","caid":"7D88165D7 |
2020-11-16 22:22:29.502 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | 14E4627932C4C3351AFC65B","sdk_version":"3.3.3","model":"SM-G610F","details":"[]","memory_total":2951749632,"af_hash":"Nzg2XzMzOD |
2020-11-16 22:22:29.502 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | AxODkwX2M1MGUyZDg4YzI3YTFmMzU","memory_remains":921231360,"seq_no":3,"app_release":"1","connection_type":"WiFi","network_availab |
2020-11-16 22:22:29.503 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | ility":"1.0","android_version_name":"8.1.0","has_telephone":true,"sd_in_tunnel":"0","time_zone":"+0500","app_name":"com.northgho |
2020-11-16 22:22:29.504 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | st.hydraclient","carrier":"Jazz","sdk_version_code":"403689","partner_carrier":"786_33801890","app_build":-606135231,"android_sd |
2020-11-16 22:22:29.505 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: | k_int":27,"error_code":"1","time":1605547339365,"device_language":"en","server_protocol":"hydra"}}                               |
2020-11-16 22:22:29.505 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: ---------------------------------------------------------
2020-11-16 22:22:29.507 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: ---------------------------------------------------------
2020-11-16 22:22:29.507 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: | Got active network info [type: WIFI[] - WIFI, state: CONNECTED/CONNECTED, reason: (unspecified), extra: "Noshair", failover: fal |
2020-11-16 22:22:29.508 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: | se, available: true, roaming: false]                                                                                             |
2020-11-16 22:22:29.508 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: ---------------------------------------------------------
2020-11-16 22:22:29.509 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: getActiveNetwork start                                                                                                          
2020-11-16 22:22:29.510 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: Got all Networks []                                                                                                             
2020-11-16 22:22:29.513 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: ---------------------------------------------------------
2020-11-16 22:22:29.514 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: | check network: 601 info: [type: WIFI_P2P[] - WIFI_P2P, state: DISCONNECTED/DISCONNECTED, reason: (unspecified), extra: (none), f |
2020-11-16 22:22:29.515 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: | ailover: false, available: true, roaming: false] cap: [ Transports: WIFI Capabilities: WIFI_P2P&NOT_RESTRICTED&TRUSTED&NOT_VPN L |
2020-11-16 22:22:29.515 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: | inkUpBandwidth>=1048576Kbps LinkDnBandwidth>=1048576Kbps]                                                                        |
2020-11-16 22:22:29.515 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: ---------------------------------------------------------
2020-11-16 22:22:29.518 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: ---------------------------------------------------------
2020-11-16 22:22:29.519 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: | check network: 641 info: [type: WIFI[] - WIFI, state: CONNECTED/CONNECTED, reason: (unspecified), extra: "Noshair", failover: fa |
2020-11-16 22:22:29.519 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: | lse, available: true, roaming: false] cap: [ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN& |
2020-11-16 22:22:29.520 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: | VALIDATED&FOREGROUND LinkUpBandwidth>=1048576Kbps LinkDnBandwidth>=1048576Kbps SignalStrength: -62]                              |
2020-11-16 22:22:29.520 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: ---------------------------------------------------------
2020-11-16 22:22:29.521 20310-20407/com.northghost.hydraclient E/USDK-ConnectionObserver: Got networks [641]                                                                                                              
2020-11-16 22:22:29.549 20310-20407/com.northghost.hydraclient E/USDK-TelemetryUrlProvi: Got domains from embedded config: event.northghost.com                                                                          
2020-11-16 22:22:29.555 20310-20407/com.northghost.hydraclient E/USDK-TelemetryUrlProvi: Return url from embedded config: https://event.northghost.com/api/report/hydra_kit state: VPNState{state='IDLE}                 
2020-11-16 22:22:30.145 20310-20407/com.northghost.hydraclient E/USDK-DefaultTrackerTra: Upload success                                                                                                                  
2020-11-16 22:22:30.160 20310-20407/com.northghost.hydraclient E/USDK-TelemetryUrlProvi: Mark url: https://event.northghost.com/api/report/hydra_kit as success: true with exception null                                
2020-11-16 22:22:30.195 20310-20407/com.northghost.hydraclient E/USDK-TelemetryUrlProvi: Mark url: https://event.northghost.com/api/report/hydra_kit as success: true with exception null                                
2020-11-16 22:22:30.241 20310-20407/com.northghost.hydraclient E/USDK-UCRService: Transport upload: sdk                                                                                                           
2020-11-16 22:22:30.300 20310-20407/com.northghost.hydraclient E/USDK-UrlRotatorImpl: Mark url   failure                                                                                                              
2020-11-16 22:22:30.301 20310-20407/com.northghost.hydraclient E/USDK-UrlRotatorImpl: com.anchorfree.partner.exceptions.EmptyBaseUrlException
        at com.anchorfree.partner.api.network.OkHttpNetworkLayer.postRequest(OkHttpNetworkLayer.java:129)
        at com.anchorfree.partner.api.impl.PartnerApiImpl.reportError(PartnerApiImpl.java:212)
        at com.anchorfree.sdk.InternalReporting$InternalTrackingTransport.startOrErrorEvent(InternalReporting.java:397)
        at com.anchorfree.sdk.InternalReporting$InternalTrackingTransport.upload(InternalReporting.java:376)
        at com.anchorfree.ucr.EventsTracker.uploadForTracker(EventsTracker.java:243)
        at com.anchorfree.ucr.EventsTracker.lambda$performUpload$2(EventsTracker.java:208)
        at com.anchorfree.ucr.-$$Lambda$EventsTracker$PhmNYXIyQ2jZNifl0WAQHw5AbBU.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2020-11-16 22:22:30.348 20310-20407/com.northghost.hydraclient E/USDK-UrlRotatorImpl: Mark url   failure                                                                                                              
2020-11-16 22:22:30.349 20310-20407/com.northghost.hydraclient E/USDK-UrlRotatorImpl: com.anchorfree.partner.exceptions.EmptyBaseUrlException
        at com.anchorfree.partner.api.network.OkHttpNetworkLayer.postRequest(OkHttpNetworkLayer.java:129)
        at com.anchorfree.partner.api.impl.PartnerApiImpl.reportError(PartnerApiImpl.java:212)
        at com.anchorfree.sdk.InternalReporting$InternalTrackingTransport.startOrErrorEvent(InternalReporting.java:397)
        at com.anchorfree.sdk.InternalReporting$InternalTrackingTransport.upload(InternalReporting.java:376)
        at com.anchorfree.ucr.EventsTracker.uploadForTracker(EventsTracker.java:243)
        at com.anchorfree.ucr.EventsTracker.lambda$performUpload$2(EventsTracker.java:208)
        at com.anchorfree.ucr.-$$Lambda$EventsTracker$PhmNYXIyQ2jZNifl0WAQHw5AbBU.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2020-11-16 22:22:33.224 9269-9403/? E/bt_btif: bta_dm_pm_btm_status hci_status=36

**Comment by timoshenkoav** [comment]
the error is TRAFFIC_EXCEED - so your user exceeded the 50mb daily traffic limit

**Comment by noshair** [comment]
how can i remove it please tell me?

**Comment by timoshenkoav** [comment]
you need to implement the purchase and make the user premium - then pay us 3$/month for each unlimited user

**Comment by noshair** [comment]
no issue i will pay you right now just tell me the easy way to pay you

**Comment by noshair** [comment]
you mean if in my carrier id "***_****" have 1k active user on play store then i have to pay you 3k$? 
or 3 doller on one carrier id 
just answer me on dollers

**Comment by timoshenkoav** [comment]
for 1k UNLIMITED users - you will pay 3k$ each month. 
For limited 50mb/day users - its free

**Comment by noshair** [comment]
please give me way or code or how can i pay you just guide me properly
