### ISSUE TITLE
CaketubeTransportException.CONNECTION_FAILED_ERROR

### ISSUE THREAD

**Issue by ScudStir** [AnchorFreePartner/hydrasdk-demo-android#106]
Hello!
On Android 4.4 VPN doesn't connect. On higher version works correct.

11-17 09:48:05.327 13977-13977/com.fast.vpn.free.secure.luckyvpn E/Error in VPN Service: a_error
11-17 09:48:18.575 13977-14232/com.fast.vpn.free.secure.luckyvpn E/USDK-DefaultTrackerTra: SSL handshake aborted: ssl=0xb82275f0: I/O error during system call, Connection reset by peer                                   
11-17 09:48:18.575 13977-14232/com.fast.vpn.free.secure.luckyvpn E/USDK-DefaultTrackerTra: javax.net.ssl.SSLException: SSL handshake aborted: ssl=0xb82275f0: I/O error during system call, Connection reset by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at com.anchorfree.ucr.transport.DefaultTrackerTransport.upload(DefaultTrackerTransport.java:145)
        at com.anchorfree.ucr.EventsTracker.uploadForTracker(EventsTracker.java:243)
        at com.anchorfree.ucr.EventsTracker.lambda$performUpload$2$EventsTracker(EventsTracker.java:208)
        at com.anchorfree.ucr.-$$Lambda$EventsTracker$n5yv4ZUOVo1Sykw_Ghihebt2qJw.run(lambda)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

**Comment by timoshenkoav** [comment]
Hello!
this error its analytics error - it should not block the connection. Please share the connection error

**Comment by ScudStir** [comment]
This is it?
11-17 11:08:31.487 6491-6491/com.fast.vpn.free.secure.luckyvpn W/ContentValues: com.northghost.caketube.exceptions.CaketubeTransportException: Connection failed
        at com.northghost.caketube.CaketubeTransport.transportError(CaketubeTransport.java:203)
        at com.northghost.caketube.CaketubeTransport.handleStateCallback(CaketubeTransport.java:158)
        at com.northghost.caketube.CaketubeTransport.updateStateString(CaketubeTransport.java:124)
        at com.northghost.caketube.CaketubeTransport.updateStateString(CaketubeTransport.java:113)
        at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:53)
        at java.lang.Thread.run(Thread.java:841)
11-17 11:08:31.487 6491-6491/com.fast.vpn.free.secure.luckyvpn E/Error in VPN Service: a_error

**Comment by timoshenkoav** [comment]
can you just send the whole logs?

**Comment by ScudStir** [comment]
[Google Nexus 5-logcat.txt](https://github.com/AnchorFreePartner/hydrasdk-demo-android/files/5573089/Google.Nexus.5-logcat.txt)
[Google Nexus 5-logcat-m13976.txt](https://github.com/AnchorFreePartner/hydrasdk-demo-android/files/5573091/Google.Nexus.5-logcat-m13976.txt)

**Comment by timoshenkoav** [comment]
Hello!
Do you use device or emulator? It does not work on emulator 4.4 due to emulator failed to open VPN tun device ERROR: Cannot open TUN in your logs
