### ISSUE TITLE
Error in VPN Service

### ISSUE THREAD

**Issue by arrafi23** [AnchorFreePartner/hydrasdk-demo-android#109]
I'm facing this error with 'Error in VPN Service'.
How to fix this..?

here is the log

W/TAG: com.anchorfree.vpnsdk.exceptions.ServiceBindFailedException: Can not bind remote service
        at com.anchorfree.vpnsdk.userprocess.servicebinding.RemoteServiceSource.bind(RemoteServiceSource.java:47)
        at com.anchorfree.vpnsdk.userprocess.RemoteVpn.bind(RemoteVpn.java:167)
        at com.anchorfree.vpnsdk.userprocess.RemoteVpn.getState(RemoteVpn.java:226)
        at com.anchorfree.sdk.RemoteVpnBolts.getState(RemoteVpnBolts.java:32)
        at com.anchorfree.sdk.UnifiedSDK.getVpnState(UnifiedSDK.java:147)
        at com.anchorfree.sdk.UnifiedSDK.addVpnStateListener(UnifiedSDK.java:80)
        at com.arinc.arvpnpro.MainActivity.onStart(MainActivity.java:56)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7986)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by timoshenkoav** [comment]
Hello!
Could you please share all the logs?

**Comment by arrafi23** [comment]
solve this problem but now I'm facing new issue. After open app when  click connect button for 1st time vpn connect successfully but after 2 secend it will show a toast "Error in VPN transport" and disconnect vpn connection. after that when i'm click again connect button now it's work perfectly.

in log just showing this :

Errorcom.anchorfree.vpnsdk.transporthydra.HydraVpnTransportException:

**Comment by timoshenkoav** [comment]
and again, please share the full logs

**Comment by arrafi23** [comment]
problem solved. Thank you
