### ISSUE TITLE
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.net.Socket.setSoTimeout(int)' on a null object reference

### ISSUE THREAD

**Issue by singhmeenu** [AnchorFreePartner/hydrasdk-demo-android#138]
Hi @timoshenkoav , using "https://d1ni8gfy25bof7.cloudfront.net" this as a base url and now getting this fatal in app
please look into it and help me out 

2021-06-15 10:43:17.631 7011-8321/com.appnextg.vidmaker E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.appnextg.vidmaker, PID: 7011
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.net.Socket.setSoTimeout(int)' on a null object reference
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.anchorfree.partner.api.network.OkHttpNetworkLayer$LoggingInterceptor.intercept(OkHttpNetworkLayer.java:394)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2021-06-15 10:47:32.167 8460-10504/com.appnextg.vidmaker A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 10504 (ble-vpn.com/...), pid 8460 (pnextg.vidmaker)

**Comment by hamaz562006** [comment]
I have 1st crash on my app , Did you find a solution?
