### ISSUE TITLE
api / backend.nortghost and https://developer.anchorfree.com/ not work?

### ISSUE THREAD

**Issue by pixymobileco** [AnchorFreePartner/hydrasdk-demo-android#180]
Hello can you give information more details for this issues? I don't get and how to get api list in backend.norghost.com ? Thanks a lot.

**Comment by pixymobileco** [comment]
also, logcat show my carrier_disabled error in hydraapp my carrier. Why?
com.northghost.hydraclient W/MainActivity: PartnerApiException{code=200message=Carrier disabledcontent=CARRIER_DISABLED}
        at unified.vpn.sdk.ExceptionExtensions.exceptionFromApi(ExceptionExtensions.java:11)
        at unified.vpn.sdk.BoltsExtensions.lambda$callbackContinue$0(BoltsExtensions.java:14)
        at unified.vpn.sdk.BoltsExtensions$$ExternalSyntheticLambda0.then(Unknown Source:2)
