### ISSUE TITLE
Provider issue

### ISSUE THREAD

**Issue by Flutter783** [AnchorFreePartner/hydrasdk-demo-android#213]

**Comment by Flutter783** [comment]
Process: com.xvvpn.privatevpn, PID: 11917
                                                                                                    java.lang.RuntimeException: Unable to get provider com.anchorfree.sdk.UnifiedSDKInitProviderMain: java.lang.SecurityException: com.xvvpn.privatevpn: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7926)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7430)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7124)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2328)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8394)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:640)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
                                                                                                    Caused by: java.lang.SecurityException: com.xvvpn.privatevpn: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5818)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                                                                                                    	at com.anchorfree.vpnsdk.userprocess.RemoteVpn.<init>(RemoteVpn.java:119)
                                                                                                    	at com.anchorfree.vpnsdk.userprocess.RemoteVpn$Builder.build(RemoteVpn.java:729)
                                                                                                    	at com.anchorfree.sdk.UnifiedSDKDeps.configure(UnifiedSDKDeps.java:64)
                                                                                                    	at com.anchorfree.sdk.SDKInitProvider.onCreate(SDKInitProvider.java:29)
                                                                                                    	at com.anchorfree.sdk.UnifiedSDKInitProviderMain.onCreate(UnifiedSDKInitProviderMain.java:3)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2621)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2590)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7921)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7430) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7124) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2328) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8394) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:640) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995) 
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14329)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2631)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2804)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1339)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1275)
