### ISSUE TITLE
RuntimeException: Unable to parse GPR configuration

### ISSUE THREAD

**Issue by goldfish07** [AnchorFreePartner/hydrasdk-demo-android#23]
java.lang.RuntimeException: Unable to parse GPR configuration

**Comment by timoshenkoav** [comment]
is this crashing your app? or just appear in logs? we are working on fixing this.

**Comment by goldfish07** [comment]
yes , my app crashing , i am debugging on samsung j810g model with android Pie One UI

**Comment by timoshenkoav** [comment]
could you please provide full stack trace and specify what sdk version do you use. your app should not crash.

**Comment by goldfish07** [comment]
because of this , i am getting popup Apps is keep stopping

**Comment by goldfish07** [comment]
Please check following logs 

2019-11-19 18:05:38.732 9163-9312/com.vpn E/GPRConfigurator: downloadConfiguration
2019-11-19 18:05:40.051 9163-9316/com.vpn E/GPRConfigurator: probeConfiguration
2019-11-19 18:05:40.052 9163-9316/com.vpn E/GPRConfigurator: Unable to parse GPR configuration
2019-11-19 18:05:40.057 9163-9316/com.vpn E/DefaultTrackerTransport: configurationError
    java.lang.RuntimeException: Unable to parse GPR configuration
        at com.northghost.ucr.gpr.GPRConfigurator.probeConfiguration(GPRConfigurator.java:124)
        at com.northghost.ucr.gpr.GPRConfigurator.access$200(GPRConfigurator.java:15)
        at com.northghost.ucr.gpr.GPRConfigurator$1.run(GPRConfigurator.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-11-19 18:05:40.686 9163-9312/com.vpn E/GPRConfigurator: downloadConfiguration
2019-11-19 18:05:40.949 9163-9359/com.vpn E/GPRConfigurator: probeConfiguration
2019-11-19 18:05:40.951 9163-9359/com.vpn E/GPRConfigurator: Unable to parse GPR configuration
2019-11-19 18:05:40.955 9163-9359/com.vpn E/DefaultTrackerTransport: configurationError
    java.lang.RuntimeException: Unable to parse GPR configuration
        at com.northghost.ucr.gpr.GPRConfigurator.probeConfiguration(GPRConfigurator.java:124)
        at com.northghost.ucr.gpr.GPRConfigurator.access$200(GPRConfigurator.java:15)
        at com.northghost.ucr.gpr.GPRConfigurator$1.run(GPRConfigurator.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-11-19 18:05:45.897 9163-9312/com.vpn E/GPRConfigurator: downloadConfiguration
2019-11-19 18:05:46.190 9163-9487/com.vpn E/GPRConfigurator: probeConfiguration
2019-11-19 18:05:46.191 9163-9487/com.vpn E/GPRConfigurator: Unable to parse GPR configuration
2019-11-19 18:05:46.195 9163-9487/com.vpn E/DefaultTrackerTransport: configurationError
    java.lang.RuntimeException: Unable to parse GPR configuration
        at com.northghost.ucr.gpr.GPRConfigurator.probeConfiguration(GPRConfigurator.java:124)
        at com.northghost.ucr.gpr.GPRConfigurator.access$200(GPRConfigurator.java:15)
        at com.northghost.ucr.gpr.GPRConfigurator$1.run(GPRConfigurator.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by timoshenkoav** [comment]
what is your sdk version?

**Comment by goldfish07** [comment]
i am using version 2.4.1

**Comment by timoshenkoav** [comment]
could you please try to run this repo project on your device. Does not have app crash with it.

**Comment by goldfish07** [comment]
repo project is not crashing on my device

**Comment by goldfish07** [comment]
i am using androidx in my app , is this may be a issue ?

**Comment by timoshenkoav** [comment]
please check your sdk integration steps. Did you do something additional. Any information would be helpfull for me to help to solve your issue

**Comment by timoshenkoav** [comment]
no, androidx should not be the issue. you can try to migrate demo app to androidx and check if it starts to crash.

**Comment by goldfish07** [comment]
Okay thank you , could you please tell me that what is my carrier id , is carrier id is my name of project in https://developer.anchorfree.com ?

**Comment by timoshenkoav** [comment]
yes, its project name, like this for "afdemo" https://monosnap.com/file/WWaTQR120nChquKVXklFIYNKs3QBjr

**Comment by goldfish07** [comment]
can you please improve documentation of https://developer.anchorfree.com adding images , it would be perfect if you do that

**Comment by timoshenkoav** [comment]
ok, thanks for the suggestion

**Comment by goldfish07** [comment]
i am 24x7 active you can contact me if you need any logs related to sdk !

**Comment by goldfish07** [comment]
i have more issue i am not able to delete my project in  https://developer.anchorfree.com , after enter private key and clicking delete button project it showing project  deleted but when i refresh page the project again appear in  https://developer.anchorfree.com please kindly help me !

**Comment by timoshenkoav** [comment]
i will contact backend team to solve your issue. will keep you updated

**Comment by goldfish07** [comment]
thank you so much there are more issue in website hope you and your team will fix this , best of luck , and thank you so much for providing your services 
may god bless you :)

**Comment by timoshenkoav** [comment]
> i have more issue i am not able to delete my project in https://developer.anchorfree.com , after enter private key and clicking delete button project it showing project deleted but when i refresh page the project again appear in https://developer.anchorfree.com please kindly help me !

what is your project id (carrier id)?

**Comment by goldfish07** [comment]
please fix that issue , i will create a fresh account !!

**Comment by timoshenkoav** [comment]
to investigate and fix the issue i need your project id(that you cannot delete)

**Comment by goldfish07** [comment]
list of project i want to delete

91_xyz123
91_7310808078
91_fghvhgvg
