### ISSUE TITLE
 crashes collected from Real Android devices 

### ISSUE THREAD

**Issue by salaheddinegit** [AnchorFreePartner/hydrasdk-demo-android#26]
if you need more details just ask, please i want to improve your amazing work 

<a href="https://ibb.co/DLspz3q"><img src="https://i.ibb.co/kMk15Yd/Screen-Shot-2019-11-24-at-4-46-42-PM.png" alt="Screen-Shot-2019-11-24-at-4-46-42-PM" border="0"></a>

source 

backtrace:
 
  #00  pc 00000000000c1558  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  01  pc 00000000000c4850  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  02  pc 00000000000c39a8  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  03  pc 000000000009b8c4  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  04  pc 000000000004f930  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  05  pc 0000000000162f68  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  06  pc 00000000001625a8  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  07  pc 000000000015d7c4  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  08  pc 000000000015c770  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  09  pc 0000000000049db0  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  10  pc 0000000000049e78  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  11  pc 0000000000052bac  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  12  pc 000000000004c0dc  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  13  pc 000000000004b38c  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  14  pc 00000000000453e8  /data/app/com.test.test--ZyVUa-aThiiTfOWwQabSw==/lib/arm64/libhydra.so
 
  15  pc 0000000000090328  /system/lib64/libc.so (__pthread_start(void*)+36)
 
  16  pc 0000000000023a28  /system/lib64/libc.so (__start_thread+68)

--------

 
  30  pc 0000000000016f23  /system/lib/libc.so (_ZL15__pthread_startPv+30)
 
  31  pc 0000000000014f43  /system/lib/libc.so (__start_thread+6)

**Comment by goldfish07** [comment]
Which lib version you are using ?

**Comment by salaheddinegit** [comment]
com.github.AnchorFreePartner.hydra-sdk-android:sdk:2.4.0

**Comment by goldfish07** [comment]
upgrade to 2.4.1

**Comment by goldfish07** [comment]
init proguard rule in app 

 #HYDRASDK
    -dontwarn okio.**
    -keep class com.anchorfree.hydrasdk.api.data.** { *; }
    -keep class com.anchorfree.hydrasdk.api.response.** { *; }
    -keep class com.anchorfree.hdr.HydraHeaderListener { *; }
    -keep class com.anchorfree.hdr.HydraConnInfo { *; }
    -keep class com.anchorfree.hdr.AFHydra { *; }
    -keepclassmembers class com.anchorfree.vpnsdk.transporthydra.HydraTransport {
         public *** protect(...);
    }
    -dontwarn com.anchorfree.vpnsdk.transporthydra.proxyservice.*
    -keepattributes InnerClasses
    -dontwarn sun.misc.**
    -dontwarn java.lang.invoke.**
    -dontwarn okhttp3.**
    -dontwarn okio.**
    -dontwarn javax.annotation.**
    -dontwarn org.conscrypt.**
    -keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase
    #DNSJava
    -dontnote org.xbill.DNS.spi.DNSJavaNameServiceDescriptor
    -dontwarn org.xbill.DNS.spi.DNSJavaNameServiceDescriptor
    -keep class com.northghost.ucr.UCRTracker$User { *; }
    -keep class * implements com.google.gson.TypeAdapterFactory
    -keep class * implements com.google.gson.JsonSerializer
    -keep class * implements com.google.gson.JsonDeserializer
    -keep class com.anchorfree.hydrasdk.SessionConfig { *; }
    -keep class com.anchorfree.hydrasdk.fireshield.** { *; }
    -keep class com.anchorfree.hydrasdk.dns.** { *; }
    -keep class com.anchorfree.hydrasdk.HydraSDKConfig { *; }
    -keep class com.anchorfree.hydrasdk.api.ClientInfo { *; }
    -keep class com.anchorfree.hydrasdk.vpnservice.connectivity.NotificationConfig { *; }

**Comment by salaheddinegit** [comment]
i have upgraded the project with this new version, but it's not possible to connect, the state stay disconnected

**Comment by goldfish07** [comment]
send me debug logs of sdk !

**Comment by salaheddinegit** [comment]
i have waited until the app was ready and watch the debug logs searching for hydra sdk, this is the logs when i click on connect 


        at java.lang.Thread.run(Thread.java:764)
2019-11-28 14:05:49.339 3312-3312/com.test.test W/MainActivity: com.anchorfree.hydrasdk.exceptions.InvalidTransportException: Transport was not set for call
        at com.anchorfree.hydrasdk.switcher.SwitchableTransport.startVpn(SwitchableTransport.java:104)
        at com.anchorfree.hydrasdk.vpnservice.AFVpnService.startVpn(AFVpnService.java:667)
        at com.anchorfree.hydrasdk.vpnservice.AFVpnService.lambda$start$5$AFVpnService(AFVpnService.java:353)
        at com.anchorfree.hydrasdk.vpnservice.-$$Lambda$AFVpnService$QRWcKcsGJlopItF3J3D6HjwaLj8.then(Unknown Source:4)
        at com.anchorfree.bolts.Task$15.run(Task.java:959)
        at com.anchorfree.bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:108)
        at com.anchorfree.bolts.Task.completeAfterTask(Task.java:950)
        at com.anchorfree.bolts.Task.continueWithTask(Task.java:747)
        at com.anchorfree.bolts.Task.continueWithTask(Task.java:759)
        at com.anchorfree.bolts.Task$13.then(Task.java:858)
        at com.anchorfree.bolts.Task$13.then(Task.java:846)
        at com.anchorfree.bolts.Task$15.run(Task.java:959)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-11-28 14:05:50.061 3481-3628/com.test.test:my.custom.vpn.process.name D/AFVpnService: Report connection start with start vpn task Task: { isCancelled false isFailed: true error com.anchorfree.hydrasdk.exceptions.TrackableException: com.anchorfree.hydrasdk.exceptions.InvalidTransportException: Transport was not set for call} 
2019-11-28 14:05:50.074 3481-3628/com.test.test:my.custom.vpn.process.name D/ConnectionEventsReporter: Tracking connection start with exception com.anchorfree.hydrasdk.exceptions.TrackableException: com.anchorfree.hydrasdk.exceptions.InvalidTransportException: Transport was not set for call
2019-11-28 14:05:50.111 3481-3628/com.test.test:my.custom.vpn.process.name D/Telemetry: Track: event: connection_start, params: Bundle[{duration=7451, server_protocol=hydra, catime=1574949942625, to_country=, reason=m_ui, hydra_base_url=https://backend.northghost.com, caid=776235F685EE4042A6E88B06EB88D532, error=InvalidTransportException, connection_type=unknown, signal_strength=0.00, hydra_carrier=afdemo, error_code=1}]
2019-11-28 14:05:50.270 3481-3628/com.test.test:my.custom.vpn.process.name D/AFVpnService: Report connection start detailed with start vpn task Task: { isCancelled false isFailed: true error com.anchorfree.hydrasdk.exceptions.TrackableException: com.anchorfree.hydrasdk.exceptions.InvalidTransportException: Transport was not set for call} 
2019-11-28 14:05:50.488 3312-4218/com.test.test D/EventHelper: Track
    action: connection_start
    timestamp:1574949950478
    props: Bundle[{device_manufacturer=Google, has_telephone=true, duration=7451, server_protocol=hydra, device_name=Google Android SDK built for x86, device_type=android, catime=1574949942625, locale=US, af_hash=YWZkZW1vX2MxOGY4ZGJhYzY5YTlhMjY, to_country=, memory_remains=832585728, reason=m_ui, app_version=1.01.101, network_class=WIFI, device_language=en, sdk_version=2.4.1, app_release=1, hydra_base_url=https://backend.northghost.com, tz=Africa/Casablanca, mcc=310, mnc=260, uid=10086, caid=776235F685EE4042A6E88B06EB88D532, idfa=cf6f53e9-b85e-427a-910e-76aa2e680c31, device_id=YWZkZW1vX2MxOGY4ZGJhYzY5YTlhMjY, time_zone=+0000, error=InvalidTransportException, model=Android SDK built for x86, app_version_code=1, app_version_name=1.01.101, af_token=, wifi_hotspot_name=<unknown ssid>, carrier=Android, connection_type=WIFI, signal_strength=0.00, af_platform=android, android_version_name=9, country=US, memory_total=1567707136, app_name=com.test.test, sdk_version_code=2918, hydra_carrier=afdemo, android_sdk_int=28, error_code=1, app_build=150978545, distinct_id=02ae1f3c-cc1e-4c7c-80ed-229806af1fe9}]
2019-11-28 14:05:53.534 3481-3628/com.test.test:my.custom.vpn.process.name D/ConnectionEventsReporter: Tracking connection start details with exception com.anchorfree.hydrasdk.exceptions.TrackableException: com.anchorfree.hydrasdk.exceptions.InvalidTransportException: Transport was not set for call
2019-11-28 14:05:53.596 3481-3628/com.test.test:my.custom.vpn.process.name D/Telemetry: Track: event: connection_start_detailed, params: Bundle[{duration=7451, server_protocol=hydra, catime=1574949942625, to_country=, reason=m_ui, hydra_base_url=https://backend.northghost.com, caid=776235F685EE4042A6E88B06EB88D532, error=InvalidTransportException, notes={"network_availability_test":[{"type":"http certificate","url":"https:\/\/bing.com","result":"UnknownHostException bing.com"},{"type":"network interface","result":"wifi"},{"type":"captive portal","url":"http:\/\/www.google.com\/generate_204","result":"UnknownHostException www.google.com"}]}, connection_type=WiFi, signal_strength=1.00, hydra_carrier=afdemo, details=[], error_code=1, network_availability=0.33}]
2019-11-28 14:05:53.656 3312-4218/com.test.test D/EventHelper: Track
    action: connection_start_detailed
    timestamp:1574949953655
    props: Bundle[{device_manufacturer=Google, has_telephone=true, duration=7451, server_protocol=hydra, device_name=Google Android SDK built for x86, device_type=android, catime=1574949942625, locale=US, af_hash=YWZkZW1vX2MxOGY4ZGJhYzY5YTlhMjY, to_country=, memory_remains=831393792, reason=m_ui, app_version=1.01.101, network_class=WIFI, device_language=en, sdk_version=2.4.1, app_release=1, hydra_base_url=https://backend.northghost.com, tz=Africa/Casablanca, mcc=310, mnc=260, uid=10086, caid=776235F685EE4042A6E88B06EB88D532, idfa=cf6f53e9-b85e-427a-910e-76aa2e680c31, device_id=YWZkZW1vX2MxOGY4ZGJhYzY5YTlhMjY, time_zone=+0000, error=InvalidTransportException, model=Android SDK built for x86, notes={"network_availability_test":[{"type":"http certificate","url":"https:\/\/bing.com","result":"UnknownHostException bing.com"},{"type":"network interface","result":"wifi"},{"type":"captive portal","url":"http:\/\/www.google.com\/generate_204","result":"UnknownHostException www.google.com"}]}, app_version_code=1, app_version_name=1.01.101, af_token=, wifi_hotspot_name=<unknown ssid>, carrier=Android, connection_type=WIFI, signal_strength=1.00, af_platform=android, android_version_name=9, country=US, memory_total=1567707136, app_name=com.test.test, sdk_version_code=2918, hydra_carrier=afdemo, details=[], android_sdk_int=28, error_code=1, app_build=150978545, network_availability=0.33, distinct_id=02ae1f3c-cc1e-4c7c-80ed-229806af1fe9}]
2019-11-28 14:05:53.663 3481-3628/com.test.test:my.custom.vpn.process.name D/AFVpnService: Finish start VPN commands sequence, isCanceled: false error: com.anchorfree.hydrasdk.exceptions.TrackableException: com.anchorfree.hydrasdk.exceptions.InvalidTransportException: Transport was not set for call
2019-11-28 14:05:53.664 3481-3628/com.test.test:my.custom.vpn.process.name D/AFVpnService: Stop vpn called in service on state VPNState{state='CONNECTING_CREDENTIALS} exception com.anchorfree.hydrasdk.exceptions.InvalidTransportException: Transport was not set for call
2019-11-28 14:05:53.665 3481-3481/com.test.test:my.custom.vpn.process.name D/HydraSdk: call com.anchorfree.vpnsdk.userprocess.RemoteVpn@2c14f0ewith VPNState{state='DISCONNECTING}vpnStateChanged with 4
2019-11-28 14:05:53.706 3481-3481/com.test.test:my.custom.vpn.process.name D/HydraSdk: call com.anchorfree.vpnsdk.userprocess.RemoteVpn@2c14f0ewith VPNState{state='IDLE}vpnStateChanged with 4
2019-11-28 14:05:53.762 3312-3312/com.test.test D/HydraSdk: call com.anchorfree.vpnsdk.userprocess.RemoteVpn@6478364with VPNState{state='DISCONNECTING}vpnStateChanged with 5
2019-11-28 14:05:53.764 3312-3312/com.test.test D/SwitchableCredentialsSource: vpnStateChanged to VPNState{state='DISCONNECTING} with HydraCredentialsSource
2019-11-28 14:05:53.870 3312-3312/com.test.test D/HydraSdk: call com.anchorfree.vpnsdk.userprocess.RemoteVpn@6478364with VPNState{state='IDLE}vpnStateChanged with 5
2019-11-28 14:05:53.895 3312-3312/com.test.test D/SwitchableCredentialsSource: vpnStateChanged to VPNState{state='IDLE} with HydraCredentialsSource
2019-11-28 14:06:03.679 3312-3480/com.test.test D/UCRService: try to find data for prefix: hydrasdk
2019-11-28 14:06:03.679 3312-3480/com.test.test D/UCRService: found data for prefix: hydrasdk
2019-11-28 14:06:03.679 3312-3480/com.test.test D/UCRService: Transport upload: hydrasdk

**Comment by goldfish07** [comment]
Not sure but don't use  androidx for now , cause i fixed this issue to backport to appcompat

**Comment by salaheddinegit** [comment]
i am not using it, 


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.github.AnchorFreePartner.hydra-sdk-android:sdk:2.4.1'
    implementation 'com.android.support:support-annotations:28.0.0' // Required Dependency by Audience Network SDK
    implementation 'com.facebook.android:audience-network-sdk:5.6.0'

    //noinspection GradleCompatible
    implementation "com.android.support:appcompat-v7:${androidSupportLibraryVersion}"
    //noinspection GradleCompatible
    implementation "com.android.support:cardview-v7:${androidSupportLibraryVersion}"
    //noinspection GradleCompatible
    implementation 'com.android.support:recyclerview-v7:25.3.1'
    implementation 'com.jakewharton:butterknife:8.8.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
}

**Comment by goldfish07** [comment]
i am sure that this repo project will work 100% fork this repo again and replace carrier id with your and try connecting !

**Comment by salaheddinegit** [comment]
okay, well thank you for your time sir

**Comment by goldfish07** [comment]
it okay welcome, but test this repo first !

**Comment by salaheddinegit** [comment]
im sorry if my English is not good, but i didn't understand very well what i need to do here, do you mean i upload the project again with this version and try it ?  from source again

**Comment by goldfish07** [comment]
yes, you have to start it from source ,cause this repo only work 100%
you only need to implement your old vpn project to this repo project and also check in between that vpn is connecting or not !  by this way you can resolve this error!

**Comment by salaheddinegit** [comment]
aaah greaaaaat ideaaa, thaaaanks a lot

**Comment by goldfish07** [comment]
i feel great you like that idea :)

**Comment by timoshenkoav** [comment]
thanks for the report, we are working on fixing these native crashes.

**Comment by salaheddinegit** [comment]
last version is not working at all : 2.4.1'  ... when you launch the app, it says user not authorized, and when you hit button connect or choose server, nothing happen 

waiting for new version .. great work my friend

**Comment by timoshenkoav** [comment]
have you tried to to login first, before hitting "Connect"?

**Comment by salaheddinegit** [comment]
Yes, you are right sir, hhh i was working with your code and i have been deleted this login button, its better to just login automatically after starting the app without clicking on any button.. so when checking with this new version of yours, i forgot to login.

sir this new version is working better on those creches ?

**Comment by timoshenkoav** [comment]
@salaheddinegit we use login button to set project id and backend usl, so you can try different with sample app. Easy version has some crashes fixed. Continue improvements
