### ISSUE TITLE
New crashes found on SDK 3.1.2

### ISSUE THREAD

**Issue by jonathansalamon** [AnchorFreePartner/hydrasdk-demo-android#42]
Hello,

Here are 2 new crashes that we have in our production app and related to the latest SDK version
``
Fatal Exception: e.n.a.i.a
Connection broken
com.northghost.caketube.CaketubeTransport.handleStateCallback (CaketubeTransport.java:170)
com.northghost.caketube.CaketubeTransport.access$600 (CaketubeTransport.java:39)
com.northghost.caketube.CaketubeTransport$1.updateStateString (CaketubeTransport.java:126)
de.blinkt.openvpn.core.OpenVPNThread.run (OpenVPNThread.java:73)
java.lang.Thread.run (Thread.java:764)
``

and
``
Fatal Exception: e.d.l.k.g
Unexpected
com.anchorfree.vpnsdk.userprocess.RemoteVpn.processStartResult (RemoteVpn.java:342)
com.anchorfree.vpnsdk.userprocess.RemoteVpn.lambda$startVpn$2 (RemoteVpn.java:162)
com.anchorfree.vpnsdk.userprocess.-$$Lambda$RemoteVpn$VvCpsgSsC-ZeNxdrSnBG2S4h56E.then (-.java:4)
com.anchorfree.bolts.Task$14.run (Task.java:914)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
java.lang.Thread.run (Thread.java:764)
Caused by e.d.l.k.a
Connection with VpnControlService was lost.
com.anchorfree.vpnsdk.userprocess.RemoteVpn.lambda$doStartVpn$12 (RemoteVpn.java:376)
com.anchorfree.vpnsdk.userprocess.-$$Lambda$RemoteVpn$qxLnAR4sR61_yCtUKfsbr4Is6o8.binderDied (-.java:4)
android.os.BinderProxy.sendDeathNotice (BinderProxy.java:844)
``

Is it possible to get a new version fixing these issues?

Thanks

**Comment by timoshenkoav** [comment]
Hello!
Connection broken is error that is thrown when connection with server was lost - e.g traffic exceed.
Need additional information how to reproduce both crashes.

**Comment by jonathansalamon** [comment]
It is a crash that is coming from our crash reporter tool and Play Store. We can't reproduce it locally but it is happening on real users

**Comment by jonathansalamon** [comment]
Hello,
we are getting some new crashes in production app that we can't reproduce but are impacting real users, find below the stacktraces:

``
java.lang.VerifyError: 
  at com.google.gson.internal.bind.TypeAdapters.<clinit> (TypeAdapters.java:239)
  at com.google.gson.Gson.<init> (Gson.java:224)
  at com.google.gson.GsonBuilder.create (GsonBuilder.java:597)
  at com.anchorfree.vpnsdk.switcher.SwitchableCredentialsSource.getGson (SwitchableCredentialsSource.java:108)
  at com.anchorfree.sdk.UnifiedSDKDeps.configure (UnifiedSDKDeps.java:41)
  at com.anchorfree.sdk.SDKInitProvider.onCreate (SDKInitProvider.java:28)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:1949)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:1923)
  at android.app.ActivityThread.installProvider (ActivityThread.java:7273)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:6813)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6699)
  at android.app.ActivityThread.access$2000 (ActivityThread.java:273)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2020)
  at android.os.Handler.dispatchMessage (Handler.java:112)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
``

``
java.lang.ExceptionInInitializerError: 
  at org.xbill.DNS.Lookup.refreshDefault (Lookup.java)
  at com.anchorfree.vpnsdk.network.probe.ProtectedDns.<clinit> (ProtectedDns.java:33)
  at com.anchorfree.sdk.SdkNetworkLayerSource$RouterConfigurer.configure (SdkNetworkLayerSource.java:53)
  at com.anchorfree.partner.api.network.OkHttpNetworkLayer.clientBuilder (OkHttpNetworkLayer.java:211)
  at com.anchorfree.partner.api.network.OkHttpNetworkLayer.buildClient (OkHttpNetworkLayer.java:179)
  at com.anchorfree.partner.api.network.OkHttpNetworkLayer.<init> (OkHttpNetworkLayer.java:63)
  at com.anchorfree.partner.api.network.OkHttpNetworkLayer$Builder.build (OkHttpNetworkLayer.java:361)
  at com.anchorfree.sdk.SdkNetworkLayerSource$DelegateNetworkLayer.lambda$buildClient$0 (SdkNetworkLayerSource.java:97)
  at com.anchorfree.sdk.-$$Lambda$SdkNetworkLayerSource$DelegateNetworkLayer$qCuXVm-NMk-WD_oPdE3FaNLHNkc.then (-.java:2)
  at com.anchorfree.bolts.Task$14.run (Task.java:914)
  at com.anchorfree.bolts.BoltsExecutors$ImmediateExecutor.execute (BoltsExecutors.java:108)
  at com.anchorfree.bolts.Task.completeImmediately (Task.java:905)
  at com.anchorfree.bolts.Task.access$000 (Task.java:34)
  at com.anchorfree.bolts.Task$10.then (Task.java:681)
  at com.anchorfree.bolts.Task$10.then (Task.java:677)
  at com.anchorfree.bolts.Task.runContinuations (Task.java:999)
  at com.anchorfree.bolts.Task.trySetResult (Task.java:1037)
  at com.anchorfree.bolts.TaskCompletionSource.trySetResult (TaskCompletionSource.java:43)
  at com.anchorfree.bolts.TaskCompletionSource.setResult (TaskCompletionSource.java:66)
  at com.anchorfree.bolts.Task$14.run (Task.java:915)
  at com.anchorfree.bolts.BoltsExecutors$ImmediateExecutor.execute (BoltsExecutors.java:108)
  at com.anchorfree.bolts.Task.completeImmediately (Task.java:905)
  at com.anchorfree.bolts.Task.access$000 (Task.java:34)
  at com.anchorfree.bolts.Task$10.then (Task.java:681)
  at com.anchorfree.bolts.Task$10.then (Task.java:677)
  at com.anchorfree.bolts.Task.runContinuations (Task.java:999)
  at com.anchorfree.bolts.Task.trySetResult (Task.java:1037)
  at com.anchorfree.bolts.TaskCompletionSource.trySetResult (TaskCompletionSource.java:43)
  at com.anchorfree.bolts.TaskCompletionSource.setResult (TaskCompletionSource.java:66)
  at com.anchorfree.bolts.Task$15$1.then (Task.java:977)
  at com.anchorfree.bolts.Task$15$1.then (Task.java:963)
  at com.anchorfree.bolts.Task$14.run (Task.java:914)
  at com.anchorfree.bolts.BoltsExecutors$ImmediateExecutor.execute (BoltsExecutors.java:108)
  at com.anchorfree.bolts.Task.completeImmediately (Task.java:905)
  at com.anchorfree.bolts.Task.access$000 (Task.java:34)
  at com.anchorfree.bolts.Task$10.then (Task.java:681)
  at com.anchorfree.bolts.Task$10.then (Task.java:677)
  at com.anchorfree.bolts.Task.runContinuations (Task.java:999)
  at com.anchorfree.bolts.Task.trySetResult (Task.java:1037)
  at com.anchorfree.bolts.TaskCompletionSource.trySetResult (TaskCompletionSource.java:43)
  at com.anchorfree.bolts.TaskCompletionSource.setResult (TaskCompletionSource.java:66)
  at com.anchorfree.bolts.Task$14.run (Task.java:915)
  at com.anchorfree.bolts.BoltsExecutors$ImmediateExecutor.execute (BoltsExecutors.java:108)
  at com.anchorfree.bolts.Task.completeImmediately (Task.java:905)
  at com.anchorfree.bolts.Task.access$000 (Task.java:34)
  at com.anchorfree.bolts.Task$10.then (Task.java:681)
  at com.anchorfree.bolts.Task$10.then (Task.java:677)
  at com.anchorfree.bolts.Task.runContinuations (Task.java:999)
  at com.anchorfree.bolts.Task.trySetResult (Task.java:1037)
  at com.anchorfree.bolts.TaskCompletionSource.trySetResult (TaskCompletionSource.java:43)
  at com.anchorfree.bolts.TaskCompletionSource.setResult (TaskCompletionSource.java:66)
  at com.anchorfree.bolts.Task$4.run (Task.java:369)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)
Caused by: java.lang.RuntimeException: 
  at org.xbill.DNS.Lookup.refreshDefault (Lookup.java:89)
  at org.xbill.DNS.Lookup.<clinit> (Lookup.java:97)
  at org.xbill.DNS.Lookup.refreshDefault (Lookup.java)
  at com.anchorfree.vpnsdk.network.probe.ProtectedDns.<clinit> (ProtectedDns.java:33)
  at com.anchorfree.sdk.SdkNetworkLayerSource$RouterConfigurer.configure (SdkNetworkLayerSource.java:53)
  at com.anchorfree.partner.api.network.OkHttpNetworkLayer.clientBuilder (OkHttpNetworkLayer.java:211)
  at com.anchorfree.partner.api.network.OkHttpNetworkLayer.buildClient (OkHttpNetworkLayer.java:179)
  at com.anchorfree.partner.api.network.OkHttpNetworkLayer.<init> (OkHttpNetworkLayer.java:63)
  at com.anchorfree.partner.api.network.OkHttpNetworkLayer$Builder.build (OkHttpNetworkLayer.java:361)
  at com.anchorfree.sdk.SdkNetworkLayerSource$DelegateNetworkLayer.lambda$buildClient$0 (SdkNetworkLayerSource.java:97)
  at com.anchorfree.sdk.-$$Lambda$SdkNetworkLayerSource$DelegateNetworkLayer$qCuXVm-NMk-WD_oPdE3FaNLHNkc.then (-.java:2)
  at com.anchorfree.bolts.Task$14.run (Task.java:914)
  at com.anchorfree.bolts.BoltsExecutors$ImmediateExecutor.execute (BoltsExecutors.java:108)
  at com.anchorfree.bolts.Task.completeImmediately (Task.java:905)
  at com.anchorfree.bolts.Task.access$000 (Task.java:34)
  at com.anchorfree.bolts.Task$10.then (Task.java:681)
  at com.anchorfree.bolts.Task$10.then (Task.java:677)
  at com.anchorfree.bolts.Task.runContinuations (Task.java:999)
  at com.anchorfree.bolts.Task.trySetResult (Task.java:1037)
  at com.anchorfree.bolts.TaskCompletionSource.trySetResult (TaskCompletionSource.java:43)
  at com.anchorfree.bolts.TaskCompletionSource.setResult (TaskCompletionSource.java:66)
  at com.anchorfree.bolts.Task$14.run (Task.java:915)
  at com.anchorfree.bolts.BoltsExecutors$ImmediateExecutor.execute (BoltsExecutors.java:108)
  at com.anchorfree.bolts.Task.completeImmediately (Task.java:905)
  at com.anchorfree.bolts.Task.access$000 (Task.java:34)
  at com.anchorfree.bolts.Task$10.then (Task.java:681)
  at com.anchorfree.bolts.Task$10.then (Task.java:677)
  at com.anchorfree.bolts.Task.runContinuations (Task.java:999)
  at com.anchorfree.bolts.Task.trySetResult (Task.java:1037)
  at com.anchorfree.bolts.TaskCompletionSource.trySetResult (TaskCompletionSource.java:43)
  at com.anchorfree.bolts.TaskCompletionSource.setResult (TaskCompletionSource.java:66)
  at com.anchorfree.bolts.Task$15$1.then (Task.java:977)
  at com.anchorfree.bolts.Task$15$1.then (Task.java:963)
  at com.anchorfree.bolts.Task$14.run (Task.java:914)
  at com.anchorfree.bolts.BoltsExecutors$ImmediateExecutor.execute (BoltsExecutors.java:108)
  at com.anchorfree.bolts.Task.completeImmediately (Task.java:905)
  at com.anchorfree.bolts.Task.access$000 (Task.java:34)
  at com.anchorfree.bolts.Task$10.then (Task.java:681)
  at com.anchorfree.bolts.Task$10.then (Task.java:677)
  at com.anchorfree.bolts.Task.runContinuations (Task.java:999)
  at com.anchorfree.bolts.Task.trySetResult (Task.java:1037)
  at com.anchorfree.bolts.TaskCompletionSource.trySetResult (TaskCompletionSource.java:43)
  at com.anchorfree.bolts.TaskCompletionSource.setResult (TaskCompletionSource.java:66)
  at com.anchorfree.bolts.Task$14.run (Task.java:915)
  at com.anchorfree.bolts.BoltsExecutors$ImmediateExecutor.execute (BoltsExecutors.java:108)
  at com.anchorfree.bolts.Task.completeImmediately (Task.java:905)
  at com.anchorfree.bolts.Task.access$000 (Task.java:34)
  at com.anchorfree.bolts.Task$10.then (Task.java:681)
  at com.anchorfree.bolts.Task$10.then (Task.java:677)
  at com.anchorfree.bolts.Task.runContinuations (Task.java:999)
  at com.anchorfree.bolts.Task.trySetResult (Task.java:1037)
  at com.anchorfree.bolts.TaskCompletionSource.trySetResult (TaskCompletionSource.java:43)
  at com.anchorfree.bolts.TaskCompletionSource.setResult (TaskCompletionSource.java:66)
  at com.anchorfree.bolts.Task$4.run (Task.java:369)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)
``

``
android.database.sqlite.SQLiteDiskIOException: 
  at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount (SQLiteConnection.java)
  at android.database.sqlite.SQLiteConnection.executeForChangedRowCount (SQLiteConnection.java:736)
  at android.database.sqlite.SQLiteSession.executeForChangedRowCount (SQLiteSession.java:754)
  at android.database.sqlite.SQLiteStatement.executeUpdateDelete (SQLiteStatement.java:64)
  at android.database.sqlite.SQLiteDatabase.delete (SQLiteDatabase.java:1577)
  at com.anchorfree.ucr.UCRContentProvider.delete (UCRContentProvider.java:35)
  at android.content.ContentProvider$Transport.delete (ContentProvider.java:343)
  at android.content.ContentResolver.delete (ContentResolver.java:1652)
  at com.anchorfree.ucr.tracker.EventsStorage.delete (EventsStorage.java:136)
  at com.anchorfree.ucr.EventsTracker.uploadForTracker (EventsTracker.java:246)
  at com.anchorfree.ucr.EventsTracker.lambda$performUpload$2 (EventsTracker.java:208)
  at com.anchorfree.ucr.-$$Lambda$EventsTracker$PhmNYXIyQ2jZNifl0WAQHw5AbBU.run (-.java:2)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)
``

``
com.anchorfree.vpnsdk.exceptions.TrackableException: 
  at com.anchorfree.vpnsdk.switcher.SwitchableCredentialsSource.wrapTrackableException (SwitchableCredentialsSource.java:151)
  at com.anchorfree.vpnsdk.switcher.SwitchableCredentialsSource.access$200 (SwitchableCredentialsSource.java:48)
  at com.anchorfree.vpnsdk.switcher.SwitchableCredentialsSource$1.failure (SwitchableCredentialsSource.java:134)
  at com.northghost.caketube.CaketubeCredentialsSource.lambda$load$2 (CaketubeCredentialsSource.java:88)
  at com.northghost.caketube.-$$Lambda$CaketubeCredentialsSource$E4OO3XBzI4gFM-TbTYE8-KhxLdA.then (-.java:2)
  at com.anchorfree.bolts.Task$14.run (Task.java:914)
  at com.anchorfree.bolts.BoltsExecutors$ImmediateExecutor.execute (BoltsExecutors.java:108)
  at com.anchorfree.bolts.Task.completeImmediately (Task.java:905)
  at com.anchorfree.bolts.Task.access$000 (Task.java:34)
  at com.anchorfree.bolts.Task$10.then (Task.java:681)
  at com.anchorfree.bolts.Task$10.then (Task.java:677)
  at com.anchorfree.bolts.Task.runContinuations (Task.java:999)
  at com.anchorfree.bolts.Task.trySetError (Task.java:1054)
  at com.anchorfree.bolts.TaskCompletionSource.trySetError (TaskCompletionSource.java:50)
  at com.anchorfree.bolts.TaskCompletionSource.setError (TaskCompletionSource.java:75)
  at com.anchorfree.bolts.Task$15$1.then (Task.java:975)
  at com.anchorfree.bolts.Task$15$1.then (Task.java:963)
  at com.anchorfree.bolts.Task$14.run (Task.java:914)
  at com.anchorfree.bolts.BoltsExecutors$ImmediateExecutor.execute (BoltsExecutors.java:108)
  at com.anchorfree.bolts.Task.completeImmediately (Task.java:905)
  at com.anchorfree.bolts.Task.continueWith (Task.java:688)
  at com.anchorfree.bolts.Task.continueWith (Task.java:700)
  at com.anchorfree.bolts.Task$15.run (Task.java:963)
  at com.anchorfree.bolts.BoltsExecutors$ImmediateExecutor.execute (BoltsExecutors.java:108)
  at com.anchorfree.bolts.Task.completeAfterTask (Task.java:950)
  at com.anchorfree.bolts.Task.access$100 (Task.java:34)
  at com.anchorfree.bolts.Task$11.then (Task.java:740)
  at com.anchorfree.bolts.Task$11.then (Task.java:736)
  at com.anchorfree.bolts.Task.runContinuations (Task.java:999)
  at com.anchorfree.bolts.Task.trySetError (Task.java:1054)
  at com.anchorfree.bolts.TaskCompletionSource.trySetError (TaskCompletionSource.java:50)
  at com.anchorfree.bolts.TaskCompletionSource.setError (TaskCompletionSource.java:75)
  at com.anchorfree.sdk.BoltsUtils$CallbackTask.failure (BoltsUtils.java:81)
  at com.anchorfree.sdk.BoltsUtils.lambda$callbackContinue$0 (BoltsUtils.java:18)
  at androidx.transition.-$$Lambda$CanvasUtils$ixEIK_rj_n4-WYbBJU-_do4_pco.then (-.java:2)
  at com.anchorfree.bolts.Task$14.run (Task.java:914)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)
Caused by: com.anchorfree.vpnsdk.exceptions.NetworkRelatedException: 
  at com.anchorfree.sdk.utils.Utils.exceptionFromApi (Utils.java:107)
  at com.anchorfree.sdk.BoltsUtils.lambda$callbackContinue$0 (BoltsUtils.java:18)
  at androidx.transition.-$$Lambda$CanvasUtils$ixEIK_rj_n4-WYbBJU-_do4_pco.then (-.java:2)
  at com.anchorfree.bolts.Task$14.run (Task.java:914)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)
Caused by: com.anchorfree.partner.exceptions.NetworkException: 
  at com.anchorfree.partner.api.network.OkHttpNetworkLayer$3.onFailure (OkHttpNetworkLayer.java:265)
  at okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.java:510)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)
Caused by: java.net.UnknownHostException: 
  at com.anchorfree.vpnsdk.network.probe.ProtectedDns.lookupHostName (ProtectedDns.java:126)
  at com.anchorfree.vpnsdk.network.probe.ProtectedDns.getAllByNameCustom (ProtectedDns.java:64)
  at com.anchorfree.vpnsdk.network.probe.ProtectedDns.lookup (ProtectedDns.java:156)
  at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress (RouteSelector.java:164)
  at okhttp3.internal.connection.RouteSelector.nextProxy (RouteSelector.java:129)
  at okhttp3.internal.connection.RouteSelector.next (RouteSelector.java:71)
  at okhttp3.internal.connection.ExchangeFinder.findConnection (ExchangeFinder.java:197)
  at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection (ExchangeFinder.java:107)
  at okhttp3.internal.connection.ExchangeFinder.find (ExchangeFinder.java:75)
  at okhttp3.internal.connection.RealCall.initExchange$okhttp (RealCall.java:245)
  at okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.java:32)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:100)
  at okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:82)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:100)
  at okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:83)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:100)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:74)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:100)
  at com.anchorfree.partner.api.network.OkHttpNetworkLayer$LoggingInterceptor.intercept (OkHttpNetworkLayer.java:389)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:100)
  at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.java:197)
  at okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.java:502)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)
``

Let us know if it will be fixed in next version

**Comment by timoshenkoav** [comment]
thanks for the report, will check

**Comment by jonathansalamon** [comment]
Hello @timoshenkoav 
We have now more details about the exception in UCRContentProvider:

``
Fatal Exception: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 778)
#################################################################
Error Code : 778 (SQLITE_IOERR_WRITE)
Caused By : Disk I/O error occurred during 'write' operation.
	(disk I/O error (code 778))
#################################################################
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:904)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1932)
       at com.anchorfree.ucr.UCRContentProvider.delete(UCRContentProvider.java:35)
       at android.content.ContentProvider$Transport.delete(ContentProvider.java:347)
       at android.content.ContentResolver.delete(ContentResolver.java:1642)
       at com.anchorfree.ucr.tracker.EventsStorage.delete(EventsStorage.java:136)
       at com.anchorfree.ucr.EventsTracker.uploadForTracker(EventsTracker.java:246)
       at com.anchorfree.ucr.EventsTracker.lambda$performUpload$2(EventsTracker.java:208)
       at com.anchorfree.ucr.-$$Lambda$EventsTracker$PhmNYXIyQ2jZNifl0WAQHw5AbBU.run(-.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
``

Is it fixed in latest released version?

**Comment by timoshenkoav** [comment]
Hello, thanks for the update. No, its not fixed yet, will keep you posted

**Comment by jonathansalamon** [comment]
Hello, is the UCRContentProvider.delete crash fixed in 3.3.1?

This represents 1441 crashes on 400 users in the last 90 days

**Comment by timoshenkoav** [comment]
Hello,
yes, it should be fixed
