### ISSUE TITLE
PartnerApiException{code=200message=carrier_id not foundcontent=BAD_REQUEST}

### ISSUE THREAD

**Issue by mwaked** [AnchorFreePartner/hydrasdk-demo-android#44]
I try to connect to VPN but it's keep give me this error:
**PartnerApiException{code=200message=carrier_id not foundcontent=BAD_REQUEST}**

Please help me, it's urgent!

**Note:** This issue happens with me only when i use Android **Pixel 2 XL** , and it's working fine on another devices!

**Comment by timoshenkoav** [comment]
Hello!
Please share your backend url, carrier id, sdk version and full sdk logs

**Comment by mwaked** [comment]
**BASE_HOST:**  "https://d2isj403unfbyl.cloudfront.net"
**BASE_CARRIER_ID:**  "IkkXbYH6GS"

**SDK versions**
implementation 'com.github.AnchorFreePartner.hydra-sdk-android:sdk:3.3.0'
implementation 'com.github.AnchorFreePartner.hydra-sdk-android:openvpn:3.3.0'

**Comment by mwaked** [comment]
@timoshenkoav  **The error log**

2020-04-16 14:14:58.557 1311-4643/? E/WifiService: Permission violation - getScanResults not allowed for uid=10323, packageName=com.rket.reocketvpn, reason=java.lang.SecurityException: UID 10323 has no location permission
2020-04-16 14:14:58.557 1311-9683/? E/WifiService: Permission violation - getScanResults not allowed for uid=10323, packageName=com.rket.reocketvpn, reason=java.lang.SecurityException: UID 10323 has no location permission
2020-04-16 14:14:59.363 27652-28388/com.rket.reocketvpn E/USDK-NetworkCallback: ---------------------------------------------------------
2020-04-16 14:14:59.363 27652-28388/com.rket.reocketvpn E/USDK-NetworkCallback: | Error on request ApiRequest{url='https://d2isj403unfbyl.cloudfront.net/user/login', method='POST', body='{"result":"BAD_REQUEST" |
2020-04-16 14:14:59.363 27652-28388/com.rket.reocketvpn E/USDK-NetworkCallback: | ,"error":"carrier_id not found"}'} BAD_REQUEST                                                                                   |
2020-04-16 14:14:59.364 27652-28388/com.rket.reocketvpn E/USDK-NetworkCallback: i.c.f.a.f: Error on request ApiRequest{url='https://d2isj403unfbyl.cloudfront.net/user/login', method='POST', body='{"result":"BAD_REQUEST","error":"carrier_id not found"}'} BAD_REQUEST
        at com.anchorfree.partner.api.g.p.a(NetworkCallback.java:40)
        at com.anchorfree.partner.api.g.p.a(NetworkCallback.java:17)
        at com.anchorfree.partner.api.h.b$c.a(OkHttpNetworkLayer.java:240)
        at o.z$b.b(RealCall.java:203)
        at o.g0.b.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-04-16 14:14:59.364 27652-28388/com.rket.reocketvpn E/USDK-NetworkCallback: ---------------------------------------------------------
2020-04-16 14:14:59.365 27652-27971/com.rket.reocketvpn E/USDK-RetryHelper: InternalRetry tag: login giving Up                                                                                              
2020-04-16 14:14:59.365 27652-27971/com.rket.reocketvpn E/USDK-RetryHelper: i.c.f.a.f: Error on request ApiRequest{url='https://d2isj403unfbyl.cloudfront.net/user/login', method='POST', body='{"result":"BAD_REQUEST","error":"carrier_id not found"}'} BAD_REQUEST
        at com.anchorfree.partner.api.g.p.a(NetworkCallback.java:40)
        at com.anchorfree.partner.api.g.p.a(NetworkCallback.java:17)
        at com.anchorfree.partner.api.h.b$c.a(OkHttpNetworkLayer.java:240)
        at o.z$b.b(RealCall.java:203)
        at o.g0.b.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by timoshenkoav** [comment]
i can see some strange value for carrier_id - IkkXbYH6GS, where is this from? Did you registered your project on https://developer.anchorfree.com/?

**Comment by mwaked** [comment]
@timoshenkoav Yes I registered my project and I am using its carrier Id.

**Comment by mwaked** [comment]
It's already working fine with all devices, but when I tried today morning on Android Pixel device, it's gave me this error!

**Comment by oxy9en** [comment]
@mwaked what the project name registered in developer console?

**Comment by mwaked** [comment]
@oxy9en Rocket VPN

**Comment by HamzaImtiazMalik** [comment]
I am also having the same issue anyone solved the issue ??

**Comment by oxy9en** [comment]
@mwaked see email in mwaked301@gmail.com

**Comment by oxy9en** [comment]
@HamzaImtiazMalik  please go to https://developer.anchorfree.com/ and create the project for your apps. We don't support more not registered projects (or not valid "carrier_id").

**Comment by goldfish07** [comment]
please close this issue and check thread #43 for solution!

**Comment by liaqateagle** [comment]
i am getting same issue check logs 
2020-04-17 17:28:39.532 15613-15833/com.smart.vpm E/USDK-NetworkCallback: ---------------------------------------------------------
2020-04-17 17:28:39.532 15613-15833/com.smart.vpm E/USDK-NetworkCallback: | Error on request ApiRequest{url='https://backend.northghost.com/user/login', method='POST', body='{"result":"BAD_REQUEST","error |
2020-04-17 17:28:39.533 15613-15833/com.smart.vpm E/USDK-NetworkCallback: | ":"carrier_id field is invalid. please register project on https://developer.anchorfree.com/"}'} BAD_REQUEST                     |
2020-04-17 17:28:39.533 15613-15833/com.smart.vpm E/USDK-NetworkCallback: com.anchorfree.partner.exceptions.RequestException: Error on request ApiRequest{url='https://backend.northghost.com/user/login', method='POST', body='{"result":"BAD_REQUEST","error":"carrier_id field is invalid. please register project on https://developer.anchorfree.com/"}'} BAD_REQUEST
        at com.anchorfree.partner.api.impl.NetworkCallback.success(NetworkCallback.java:40)
        at com.anchorfree.partner.api.impl.NetworkCallback.success(NetworkCallback.java:17)
        at com.anchorfree.partner.api.network.OkHttpNetworkLayer$3.onResponse(OkHttpNetworkLayer.java:240)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2020-04-17 17:28:39.534 15613-15833/com.smart.vpm E/USDK-NetworkCallback: ---------------------------------------------------------

**Comment by goldfish07** [comment]
have tried solution mentioned in #43 ?

**Comment by anas1991mohammad** [comment]
hello ,
i have same issue from 3 days ago ,please help me

**Comment by goldfish07** [comment]
@anas1991mohammad  for solution visit #43

**Comment by anas1991mohammad** [comment]
its not solve i try it but not solved

**Comment by goldfish07** [comment]
@anas1991mohammad  error logs ?

**Comment by anas1991mohammad** [comment]
Error on request ApiRequest{url='https://backend.northghost.com/user/login', method='POST', body='{"result":"BAD_REQUEST","error":"carrier_id field is invalid. please register project on https://developer.anchorfree.com/"}'} BAD_REQUEST
