### ISSUE TITLE
New Carrier id dose't work

### ISSUE THREAD

**Issue by mwaked** [AnchorFreePartner/hydrasdk-demo-android#58]
I registered a new project on https://developer.anchorfree.com/ ,
but the Carrier Id give me unauthorized when i try to make login!

Can you send me which email can i send to you my carrier id to check?
Or you can check my account mwaked301@gmail.com

**Comment by noshair** [comment]
where did you paste that?
and what's the error

**Comment by mwaked** [comment]
**Gradle**
```
    defaultConfig {
        buildConfigField "String", "BASE_HOST", "\"https://d2isj403unfbyl.cloudfront.net\""
        buildConfigField "String", "BASE_CARRIER_ID", "\"012011_firevpn\""
        buildConfigField "String", "BASE_OAUTH_METHOD", "\"anonymous\""
}
```

**BaseApplication**
```
  private fun initHydraSdk() {

        createNotificationChannel()
        val clientInfo = ClientInfo.newBuilder()
                .baseUrl(BuildConfig.BASE_HOST)
                .carrierId(BuildConfig.BASE_CARRIER_ID)
                .build()
        val transportConfigList: MutableList<TransportConfig> = ArrayList()
        transportConfigList.add(HydraTransportConfig.create())
        transportConfigList.add(OpenVpnTransportConfig.tcp())
        transportConfigList.add(OpenVpnTransportConfig.udp())
        UnifiedSDK.update(transportConfigList, CompletableCallback.EMPTY)
        val config = UnifiedSDKConfig.newBuilder().idfaEnabled(false).build()
        unifiedSDK = UnifiedSDK.getInstance(clientInfo, config)
        val notificationConfig = NotificationConfig.newBuilder()
                .title(resources.getString(R.string.app_name))
                .channelId(CHANNEL_ID)
                .build()
        UnifiedSDK.update(notificationConfig)
        UnifiedSDK.setLoggingLevel(Log.VERBOSE)
    }
```

**Error Log:**
E/USDK-NetworkCallback: | Error on request ApiRequest{url='https://d2isj403unfbyl.cloudfront.net/user/countries?access_token=&type=hydra-tcp', method='GET |
2020-05-12 23:05:58.927 18678-19271/? E/USDK-NetworkCallback: | ', body='{"result":"NOT_AUTHORIZED"}'} NOT_AUTHORIZED

**Comment by timoshenkoav** [comment]
you need to login first

**Comment by mwaked** [comment]
@timoshenkoav  It's give me unauthorized when i try to login.

**Comment by timoshenkoav** [comment]
please send login error, on prev message i can see unauthorized on countries, not login

**Comment by mwaked** [comment]
@timoshenkoav 

020-05-12 23:16:46.069 23792-23988/? E/USDK-NetworkCallback: ---------------------------------------------------------
2020-05-12 23:16:46.069 23792-23988/? E/USDK-NetworkCallback: | Error on request ApiRequest{url='https://d2isj403unfbyl.cloudfront.net/user/login', method='POST', body='{"result":"ERROR","erro |
2020-05-12 23:16:46.070 23792-23988/? E/USDK-NetworkCallback: | r":"Internal error"}'} ERROR                                                                                                     |
2020-05-12 23:16:46.070 23792-23988/? E/USDK-NetworkCallback: f.a.f.a.f: Error on request ApiRequest{url='https://d2isj403unfbyl.cloudfront.net/user/login', method='POST', body='{"result":"ERROR","error":"Internal error"}'} ERROR
        at com.anchorfree.partner.api.g.p.a(NetworkCallback.java:7)
        at com.anchorfree.partner.api.g.p.a(NetworkCallback.java:1)
        at com.anchorfree.partner.api.h.b$c.a(OkHttpNetworkLayer.java:4)
        at j.z$b.b(RealCall.java:3)
        at j.g0.b.run(NamedRunnable.java:3)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)

**Comment by timoshenkoav** [comment]
what is your carrier id?

**Comment by mwaked** [comment]
@timoshenkoav 
carrier id: 012011_hotvpn

**Comment by oxy9en** [comment]
You made the project with type "private_vpn". For this type, you should add users manually to the project. For public VPN need to create a "public VPN" project.

**Comment by mwaked** [comment]
@oxy9en Thanks, it's working fine now after created public VPN project
