### ISSUE TITLE
Some servers not connecting on VPN SDK

### ISSUE THREAD

**Issue by beratsenv** [AnchorFreePartner/hydrasdk-demo-android#81]
Hello again, 
in my users said: (india) not connected anymore  and I tried connect but I think last your revision maybe have bugs.
And when I connect some websites not getting...
Thanks a lot. Can you look at this issue?

**Comment by beratsenv** [comment]
Also my user reviewed not download server list especially for India. Is that trouble on India government.
Everything Ok since yesterday but morning not work anymore on India especially get server list

**Comment by timoshenkoav** [comment]
Hello!
Could you please provide logs? SDK/Android Version?

**Comment by beratsenv** [comment]
> Hello!
> Could you please provide logs? SDK/Android Version?

Hello my users said almost every android version and I checked firebase but  tried  just now latest hydra sdk version and problem not solving in your sdk i think server list very very very slowed down on api. 

my sdk version 3.0 

In this month we will migrate new version but not yet.

**Comment by timoshenkoav** [comment]
So you can reproduce the issue with demo app from this repo? could you please send logs?

**Comment by beratsenv** [comment]
> So you can reproduce the issue with demo app from this repo? could you please send logs?

Here is demo app just try and on google play and server list very late and any connect a server maybe not working today
Here
https://play.google.com/store/apps/details?id=com.darkweb.genesisvpn

Git repo

https://github.com/msmannan00/Genesis-VPN-Android

**Comment by timoshenkoav** [comment]
servers loads fast for me on your app. It takes about 1-2s to load

**Comment by beratsenv** [comment]
> servers loads fast for me on your app. It takes about 1-2s to load

Thats interesting I don't really understand so, why users get very lazy serverlist ? Oh your link very fast! 
Is this permanent link right?

**Comment by beratsenv** [comment]
Hello, I think India blocked your link in today
here is the news: https://www.cnet.com/news/india-bans-100-more-chinese-linked-apps-including-pubg-and-vpn-for-tiktok/
https://www.91mobiles.com/hub/pubg-mobile-ban-india-vpn/ 

Ohhh **What should we do now? I think even PUBG is banned because of this.**

**Comment by timoshenkoav** [comment]
do you have logs? is the error is on api side or in connection to vpn server? can you do login/get countries list?

**Comment by beratsenv** [comment]
It works smoothly in Europe. However, since India government banned Tiktok and and some VPN apps, I think there seems to be a problem on the api side (I think banned your api domain by India). Normally, I can easily provide information in my own country within seconds. According to my Indian users, the server list is not going down anyway. I lost a lot of users today. Im so sorry about that. In my firebase crashlictys everything is fine. No log for api side issue (in europa) Here. Also,  I have anonymous login method for your the api. In dashboard everything is OK, but I don't understand. But reviews show off Indian people not get serverlist. I will try with Indian ISP...

**Comment by beratsenv** [comment]
`2020-09-03 22:32:23.666 10780-2914/com.free.vpn.ninja W/System.err: java.io.FileNotFoundException: https://s3.amazonaws.com/af-gpr/hydra_kit.DEFAULT.1.conf
2020-09-03 22:32:23.666 10780-2914/com.free.vpn.ninja W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
2020-09-03 22:32:23.666 10780-2914/com.free.vpn.ninja W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
2020-09-03 22:32:23.666 10780-2914/com.free.vpn.ninja W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
2020-09-03 22:32:23.666 10780-2914/com.free.vpn.ninja W/System.err:     at com.northghost.ucr.RequestHelper.close(RequestHelper.java:78)
2020-09-03 22:32:23.666 10780-2914/com.free.vpn.ninja W/System.err:     at com.northghost.ucr.gpr.GPRConfigurator$1.run(GPRConfigurator.java:114)
2020-09-03 22:32:23.666 10780-2914/com.free.vpn.ninja W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
2020-09-03 22:32:23.666 10780-2914/com.free.vpn.ninja W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2020-09-03 22:32:23.666 10780-2914/com.free.vpn.ninja W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2020-09-03 22:32:23.666 10780-2914/com.free.vpn.ninja W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2020-09-03 22:32:23.666 10780-2914/com.free.vpn.ninja W/System.err:     at java.lang.Thread.run(Thread.java:761)
2020-09-03 22:32:32.547 10780-11036/com.free.vpn.ninja D/UCRService: performUpload
2020-09-03 22:32:32.550 10780-11036/com.free.vpn.ninja D/UCRService: try to find data for prefix: hydrasdk
2020-09-03 22:32:32.550 10780-11036/com.free.vpn.ninja D/UCRService: found data for prefix: hydrasdk
2020-09-03 22:32:32.550 10780-11036/com.free.vpn.ninja D/UCRService: Transport upload: hydrasdk
2020-09-03 22:32:32.550 10780-11036/com.free.vpn.ninja D/DefaultTrackerTransport: upload
2020-09-03 22:32:32.550 10780-11036/com.free.vpn.ninja D/DefaultTrackerTransport: Empty endpoint skip upload
2020-09-03 22:32:32.550 10780-11036/com.free.vpn.ninja D/UCRService: Transport upload: hydrasdk
2020-09-03 22:32:32.555 10780-2970/com.free.vpn.ninja D/api.OkHttpNetworkLayer: Requesting https://awebhtpo3u8g5t.ecoweb-network.com/user/perf
2020-09-03 22:32:32.555 10780-2970/com.free.vpn.ninja D/api.OkHttpNetworkLayer: Body app_version=1.0.6&user_ip=178.162.202.15&time=0&access_token=1e3q3pqgd80bb10hjqcrcn02vd98ra89eg2asoi4629vgioj7npj&test_name=VPN%20node%20ping&optimal=false&app=com.free.vpn.ninja&vpn_ip=78.129.190.101&test_ip=78.129.190.101
2020-09-03 22:32:32.658 10998-11041/com.free.vpn.ninja D/HydraTransport: Header event: B:9468,4775 <null>
2020-09-03 22:32:32.859 10998-11041/com.free.vpn.ninja D/HydraTransport: Header event: B:9507,4962 <null>
2020-09-03 22:32:32.921 10998-11041/com.free.vpn.ninja D/HydraTransport: Header event: B:14804,5582 <null>
2020-09-03 22:32:33.491 10780-2970/com.free.vpn.ninja D/api.OkHttpNetworkLayer: Response received for https://awebhtpo3u8g5t.ecoweb-network.com/user/perf in 936.3ms code: 200
2020-09-03 22:32:34.138 10998-11041/com.free.vpn.ninja D/HydraTransport: Header event: B:15463,5962 <null>
2020-09-03 22:32:34.593 10998-11041/com.free.vpn.ninja D/HydraTransport: Header event: B:15810,6906 <null>
2020-09-03 22:32:53.283 10998-11043/com.free.vpn.ninja V/HydraTransport: Connection log: [{"server_ip": "78.129.190.101", "server_port": 443, "duration_ms": 73, "route": "default", "error_code": 0, "state": "CONNECTED (TCP handshake completed)", "state_code": 1}, {"server_ip": "78.129.190.101", "server_port": 443, "duration_ms": 149, "route": "default", "error_code": 0, "state": "FIRST_BYTE_RD (TLS handshake started)", "state_code": 2}, {"server_ip": "78.129.190.101", "server_port": 443, "duration_ms": 228, "route": "default", "error_code": 0, "state": "READY_PAYLOAD (TLS handshake completed)", "state_code": 3}, {"server_ip": "78.129.190.101", "server_port": 443, "duration_ms": 330, "route": "default", "error_code": 0, "state": "READY_CARRIER (transport is ready to send data)", "state_code": 4}]
2020-09-03 22:32:53.283 10998-11043/com.free.vpn.ninja D/HydraTransport: Get connection info in Thread:533
2020-09-03 22:32:53.283 10998-11043/com.free.vpn.ninja D/HydraTransport: Read connection for type 1 [ConnectionInfo{domain='', ips=[78.129.190.101]}]
2020-09-03 22:32:53.283 10998-11043/com.free.vpn.ninja D/HydraTransport: Get connection info in Thread:533
2020-09-03 22:32:53.284 10998-11043/com.free.vpn.ninja D/HydraTransport: Read connection for type 2 []`

**Comment by timoshenkoav** [comment]
from this log i can see it has very old sdk and it gets connected

**Comment by beratsenv** [comment]
> from this log i can see it has very old sdk and it gets connected

In this night we working on new api is this work on India?

**Comment by timoshenkoav** [comment]
@beratsenv please check this issue comments https://github.com/AnchorFreePartner/hydrasdk-demo-android/issues/82
