### ISSUE TITLE
Error In connecting server

### ISSUE THREAD

**Issue by Shvet** [AnchorFreePartner/hydrasdk-demo-android#87]
```
 E/USDK-UrlRotatorImpl: Mark url https://backend.northghost.com failure                                                                                 
09-15 15:32:25.451 14416-14660/com.borcua.vpnpro E/USDK-UrlRotatorImpl: com.anchorfree.partner.exceptions.NetworkException: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x8737b400: I/O error during system call, Connection reset by peer
        at com.anchorfree.partner.api.network.OkHttpNetworkLayer$2.onFailure(OkHttpNetworkLayer.java:277)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:211)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x8737b400: I/O error during system call, Connection reset by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.anchorfree.partner.api.network.OkHttpNetworkLayer$LoggingInterceptor.intercept(OkHttpNetworkLayer.java:376)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```

I am running SDK version 3.3.2.
It was working fine yesterday but now every time i run app, i get this error.Also It has login problem too, as it gives errors like `InternalRetry tag: login retry step:1 ` .

**Comment by timoshenkoav** [comment]
Hello!
Could you please share backend url you use?

**Comment by Shvet** [comment]
Hello, @timoshenkoav  
Thanks for your reply. This is urls i am using right now.
```
urlList.add("https://backend.northghost.com");
urlList.add("https://d2isj403unfbyl.cloudfront.net");
```

**Comment by timoshenkoav** [comment]
please remove https://backend.northghost.com and dont use it

**Comment by Shvet** [comment]
Should i user other server? like second one?

**Comment by timoshenkoav** [comment]
Yes, also you can create you own urls - https://pango.gitbook.io/pango-platform/resources/how-to/aws-cloudfront-distribution

**Comment by Shvet** [comment]
```
09-15 16:27:01.825 21608-21685/com.borcua.vpnpro E/USDK-RemoteVpn: Death link does not exist                                                                                                       
09-15 16:27:01.826 21608-21685/com.borcua.vpnpro E/USDK-RemoteVpn: java.util.NoSuchElementException: Death link does not exist
        at android.os.BinderProxy.unlinkToDeath(Native Method)
        at com.anchorfree.vpnsdk.userprocess.RemoteVpn.safeUnlinkDeath(RemoteVpn.java:404)
        at com.anchorfree.vpnsdk.userprocess.RemoteVpn.access$600(RemoteVpn.java:64)
        at com.anchorfree.vpnsdk.userprocess.RemoteVpn$4.onComplete(RemoteVpn.java:427)
        at com.anchorfree.vpnsdk.vpnservice.IRemoteCompletableCallback$Stub.onTransact(IRemoteCompletableCallback.java:49)
        at android.os.Binder.execTransact(Binder.java:467)

```
Ok, I will try that, I got this error when disconnected from vpn.

**Comment by timoshenkoav** [comment]
its not an error. its just a log output. you can skip it

**Comment by Shvet** [comment]
Ok, I will try to use AWS Option.
