### ISSUE TITLE
My 3.1.1 version App is Crashing!

### ISSUE THREAD

**Issue by brittle123** [AnchorFreePartner/hydrasdk-demo-android#90]
Hello Sir ! i made an application few months back in which i used your 3.1.1 version sdk and published on playstore,.. now it's crashing,.. have you changed all authentication criteria for even the previous sdk versions. that's not fair sir. Should i've to buy your sdk's for now!,... or i can use your previously made free sdk version 3.1.1?
My App crashes when i  click on chose location server and throws this error.

 Process: com.virtoxed.BoostVPN, PID: 12753
    java.lang.ArrayIndexOutOfBoundsException: length=21; index=-1
        at com.virtoxed.BoostVPN.adapter.RegionListAdapter.onBindViewHolder(RegionListAdapter.java:66)
        at com.virtoxed.BoostVPN.adapter.RegionListAdapter.onBindViewHolder(RegionListAdapter.java:25)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:16728)
        at android.view.ViewGroup.layout(ViewGroup.java:5452)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
        at android.view.View.layout(View.java:16728)
        at android.view.ViewGroup.layout(ViewGroup.java:5452)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16728)
        at android.view.ViewGroup.layout(ViewGroup.java:5452)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16728)
        at android.view.ViewGroup.layout(ViewGroup.java:5452)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2728)
        at android.view.View.layout(View.java:16728)
        at android.view.ViewGroup.layout(ViewGroup.java:5452)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2288)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2025)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1174)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6241)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
        at android.view.Choreographer.doCallbacks(Choreographer.java:676)
        at android.view.Choreographer.doFrame(Choreographer.java:606)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:168)
        at android.app.ActivityThread.main(ActivityThread.java:5845)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by timoshenkoav** [comment]
Hello!
Crash is not on SDK side. Crash is inside your code. You try to get list element on index "-1". No auth changes in the sdk, you can continue to use 3.1.1 - but its always better to use the latest version

**Comment by brittle123** [comment]
Sir thankyou for replying me but how can i use your latest version for
free...i've 5000+ downloads on playstore?

**Comment by timoshenkoav** [comment]
you can use last version for free as before - but free users have 50mb per day limit now. To enable unlimited users please refer to https://github.com/AnchorFreePartner/hydrasdk-demo-android/issues/89

**Comment by brittle123** [comment]
Sir could you please tell me that which sdk version of urs provide the
unlimited data,... and please do me a favour,, send me its documentation
aswel from which i can code. Thanks in advance. Regards

**Comment by brittle123** [comment]
previous sdk version which is totally free and provide unlimited data.

**Comment by timoshenkoav** [comment]
users has limit of 50mb per day. It does not depend on sdk version.

**Comment by brittle123** [comment]
https://play.google.com/store/apps/details?id=supervpnfree.vpnmaster.unblock_proxy

Sir this is the app of my friend who used your 2.4.1 sdk version,.. i
connected any server of this app and downloaded pubg game which is of about
2gb. and Download completed. how?

**Comment by timoshenkoav** [comment]
old projects are not completely migrated yet. We are migrating projects step by step. Soon it will also has limit of 50mb/day

**Comment by brittle123** [comment]
And i'm using your 3.1.1 sdk version,... when i connected to any server and
downloaded only UC Browser app which is of about 60mb... and then i can't
even reconnect my vpn to any of ur server again.

**Comment by brittle123** [comment]
So it means there is no chance of getting unlimited data ever again!

**Comment by Yahi143** [comment]
Uc pubg free

**Comment by Yahi143** [comment]
Uc pubg free
