### ISSUE TITLE
My App is not working i am getting this issue 

### ISSUE THREAD

**Issue by 007cherukuri** [AnchorFreePartner/hydrasdk-demo-android#99]
2020-10-27 19:44:56.999 2562-3071/com.redlapdigital.highspeedvpn.vpn E/USDK-RetryHelper: com.anchorfree.partner.exceptions.NetworkException: java.net.UnknownHostException: d2isj403unfbyl.cloudfront.net
        at com.anchorfree.partner.api.network.OkHttpNetworkLayer$2.onFailure(OkHttpNetworkLayer.java:277)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:211)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.UnknownHostException: d2isj403unfbyl.cloudfront.net
        at com.anchorfree.vpnsdk.network.probe.ProtectedDns.lookupHostName(ProtectedDns.java:110)
        at com.anchorfree.vpnsdk.network.probe.ProtectedDns.getAllByNameCustom(ProtectedDns.java:48)
        at com.anchorfree.vpnsdk.network.probe.ProtectedDns.lookup(ProtectedDns.java:142)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:215)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.anchorfree.partner.api.network.OkHttpNetworkLayer$LoggingInterceptor.intercept(OkHttpNetworkLayer.java:376)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by timoshenkoav** [comment]
@007cherukuri please provide more information. as java.net.UnknownHostException means that you dont have internet connection. Its not sdk exception

**Comment by 007cherukuri** [comment]
> @007cherukuri please provide more information. as java.net.UnknownHostException means that you dont have internet connection. Its not sdk exception

It's not working in UAE country I have an good internet connection.

**Comment by timoshenkoav** [comment]
@007cherukuri try to create another URL. refer https://github.com/AnchorFreePartner/hydrasdk-demo-android/issues/73
